// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfnHEIkOY_vdGe_SIPv51BgKDO1Zneiiw',
    appId: '1:605512707529:web:976aa5838ad65c0c39cc18',
    messagingSenderId: '605512707529',
    projectId: 'flutterfirebasecompleteguid',
    authDomain: 'flutterfirebasecompleteguid.firebaseapp.com',
    storageBucket: 'flutterfirebasecompleteguid.firebasestorage.app',
    measurementId: 'G-5KKHKE52XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVqecYA3ErAHRSr-b3RJLeVxHzLahgWwo',
    appId: '1:605512707529:android:fe05a38bdda1bb2f39cc18',
    messagingSenderId: '605512707529',
    projectId: 'flutterfirebasecompleteguid',
    storageBucket: 'flutterfirebasecompleteguid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNbshl8le6AU0CUVkbDbqXvS_QXPMp9AI',
    appId: '1:605512707529:ios:50181a0fe132c12939cc18',
    messagingSenderId: '605512707529',
    projectId: 'flutterfirebasecompleteguid',
    storageBucket: 'flutterfirebasecompleteguid.firebasestorage.app',
    iosClientId: '605512707529-kq48rf7unvei9i8k2ovqeuvn4qtupvm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTask',
  );
}
